---
name: Release process-watcher binary

"on":
  push:
    tags:
      - "v*"

jobs:
  #
  # Linux
  #
  release-linux:
    name: Release process-watcher on Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ${{ fromJson(inputs.archs || '["amd64", "arm64"]') }}
    env:
      GOOS: linux
      GOARCH: ${{ matrix.arch }}
      CGO_ENABLED: 0
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          path: 'process-watcher'
          ref: ${{ inputs.tag }}

      - name: Sanity check
        working-directory: 'process-watcher'
        run: |
          git rev-parse --verify HEAD
          git status

      - name: Build binary
        working-directory: 'process-watcher'
        run: go build -ldflags '-extldflags "-static"' -o ../build/process-watcher .

      - name: Bundle binary in archive
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          directory: build
          filename: process-watcher-${{ env.GOOS }}-${{ env.GOARCH }}.zip

      - name: Release
        if: ${{ inputs.publish || startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          files: build/*.zip
          name: ${{ inputs.tag || github.ref_name }}
          tag_name: ${{ inputs.tag || github.ref_name }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
